"use client";

/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useCallback, useEffect, useState } from "react";

type Profile = { id: string; display_name: string; email: string | null; phone: string | null; whatsapp_number: string | null; access_level: string; employment_status: string; timezone: string; color_hex: string; google_staff_name: string | null };
async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Request failed."); return data as T; }

export default function StaffProfilesWorkspace() {
  const [profiles, setProfiles] = useState<Profile[]>([]), [editor, setEditor] = useState<Profile | "new" | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [search, setSearch] = useState("");
  const load = useCallback(async () => { try { setError(""); setProfiles(await json<Profile[]>("/api/staff-profiles")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load staff."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await json("/api/staff-profiles", { method: editor === "new" ? "POST" : "PATCH", body: JSON.stringify(editor === "new" ? values : { ...values, id: editor?.id }) }); setEditor(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save staff."); } finally { setBusy(false); } }
  const shown = profiles.filter(item => [item.display_name, item.google_staff_name, item.access_level, item.employment_status].join(" ").toLowerCase().includes(search.toLowerCase()));
  const editing = editor && editor !== "new" ? editor : null;
  return <div className="staff-profiles-workspace"><div className="property-toolbar"><div><small>OPERATIONAL DIRECTORY</small><h2>Staff profiles</h2><p>Roster, SMS, assignments and reporting data. Google Team remains the login source.</p></div><button className="primary-action" onClick={() => setEditor("new")}>＋ Add Staff</button></div>{error && <p className="workspace-error">{error}</p>}<div className="staff-profile-tools"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search staff, access or status" /><span>{profiles.filter(item => item.employment_status === "Active").length} active</span></div><div className="staff-profile-list">{shown.map(item => <button key={item.id} onClick={() => setEditor(item)}><i style={{ background: item.color_hex }}>{item.display_name.slice(0,1).toUpperCase()}</i><div><strong>{item.display_name}</strong><small>{item.access_level} · Login match: {item.google_staff_name || item.display_name}</small></div><span className={item.employment_status.toLowerCase()}>{item.employment_status}</span><em>{item.phone || item.whatsapp_number ? "SMS ready" : "Phone needed"}</em></button>)}</div>{editor && <div className="creator-backdrop"><form className="staff-profile-editor" onSubmit={save}><header><div><small>STAFF PROFILE</small><h2>{editor === "new" ? "Add staff" : "Edit staff"}</h2></div><button type="button" onClick={() => setEditor(null)}>×</button></header><div className="roster-editor-grid"><label>Display name<input name="display_name" required defaultValue={editing?.display_name || ""} /></label><label>Google login name<input name="google_staff_name" required defaultValue={editing?.google_staff_name || editing?.display_name || ""} /></label><label>Access<select name="access_level" defaultValue={editing?.access_level || "Team"}><option>Master</option><option>Supervisor</option><option>Team</option></select></label><label>Status<select name="employment_status" defaultValue={editing?.employment_status || "Active"}><option>Active</option><option>Inactive</option><option>Leave</option></select></label><label>Phone<input name="phone" inputMode="tel" defaultValue={editing?.phone || ""} placeholder="947XXXXXXXX" /></label><label>WhatsApp<input name="whatsapp_number" inputMode="tel" defaultValue={editing?.whatsapp_number || ""} placeholder="947XXXXXXXX" /></label><label>Email<input name="email" type="email" defaultValue={editing?.email || ""} /></label><label>Profile color<input name="color_hex" type="color" defaultValue={editing?.color_hex || "#E98A15"} /></label></div><div className="login-source-note"><strong>Login remains in Google</strong><p>This profile does not create or change a PIN. Its Google login name must match the Team sheet Name value.</p></div><footer><button type="button" onClick={() => setEditor(null)}>Cancel</button><button className="primary-action" disabled={busy}>{busy ? "Saving…" : "Save profile"}</button></footer></form></div>}</div>;
}
