"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useEffect, useState } from "react";
import { createTask, fetchProperties, updateTaskStatus } from "../../lib/api";

const taskTypes = ["FIT Booking", "TA Inquiry", "TA Booking", "TA Follow-up", "Room Block", "Rate Update", "Booking Info", "Promotions", "OTA Issue", "Guest Message", "Other"];
const sources = ["Phone Call", "WhatsApp Group", "Email", "OTA", "Client Portal", "Staff Dashboard", "Scheduled"];

export default function TaskCreatorModal({ open, onClose, staff, shift, onCreated }: any) {
  const [properties, setProperties] = useState<string[]>([]); const [property, setProperty] = useState(""); const [type, setType] = useState("Room Block"); const [source, setSource] = useState("Phone Call"); const [priority, setPriority] = useState("Normal"); const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (open) fetchProperties().then(setProperties).catch((e) => setError(e.message)); }, [open]);
  async function save(start: boolean) { if (!property) return setError("Please select a property."); try { setBusy(start ? "start" : "create"); setError(""); const result: any = await createTask({ taskType: type, source, property, priority, subject: title || type, note, staffName: staff.name, staffPhone: staff.phone || staff.whatsapp || "", shift: shift?.shift || "" }); const id = String(result?.taskId || result?.id || result?.task?.id || ""); if (start && id) await updateTaskStatus(id, "In Progress", staff.name); await onCreated(); onClose(); setTitle(""); setNote(""); setProperty(""); } catch (e: any) { setError(e.message || "Unable to create task"); } finally { setBusy(""); } }
  if (!open) return null;
  return <div className="creator-backdrop" onMouseDown={onClose}><section className="task-creator" onMouseDown={e => e.stopPropagation()}><header><div><small>UNIVERSAL TASK CREATOR</small><h2>Create operational task</h2><p>Confirm the essentials. The system records the rest.</p></div><button onClick={onClose}>×</button></header><div className="creator-grid"><label><span>Source</span><select value={source} onChange={e => setSource(e.target.value)}>{sources.map(x => <option key={x}>{x}</option>)}</select></label><label><span>Property *</span><select value={property} onChange={e => setProperty(e.target.value)}><option value="">Select property</option>{properties.map(x => <option key={x}>{x}</option>)}</select></label><label><span>Task type</span><select value={type} onChange={e => setType(e.target.value)}>{taskTypes.map(x => <option key={x}>{x}</option>)}</select></label><label><span>Priority</span><select value={priority} onChange={e => setPriority(e.target.value)}><option>Normal</option><option>High</option></select></label><label className="wide"><span>Title / Subject</span><input value={title} onChange={e => setTitle(e.target.value)} placeholder={type}/></label><label className="wide"><span>Description / Notes</span><textarea value={note} onChange={e => setNote(e.target.value)} placeholder="What needs to be done?"/></label></div>{error && <p className="workspace-error">{error}</p>}<footer><button onClick={onClose}>Cancel</button><button disabled={!!busy} onClick={() => save(false)}>{busy === "create" ? "Creating…" : "Create Task"}</button><button className="primary-action" disabled={!!busy} onClick={() => save(true)}>{busy === "start" ? "Starting…" : "Create & Start"}</button></footer></section></div>;
}
